### ISSUE TITLE
Long application titles make the main application panel "scroll"

### ISSUE THREAD

**Issue by busbus** [Esri/photo-survey#31]
This isn't the greatest usability feature on ipad - the scrollbar doesn't show up so you have to hold and drag the panel around to answer the questions.

Lock the panel would be a better user experience.

**Comment by MikeTschudi** [comment]
Title wraps if it has word break points such as spaces or hyphens. If a line--wrapped or not--has too many characters to fit, it will be cut off.  E.g., the title "Long application titlesmakethemainapplication panel scroll" will appear as
```
Long application 
titlesmakethemainapp 
panel scroll
```
because the extra-long word "titlesmakethemainapplication" is cut off on the right
