### ISSUE TITLE
IE 11 doesn't allow 3rd party cookies by default - failure to login using twitter

### ISSUE THREAD

**Issue by ChrisBuscaglia** [Esri/photo-survey#32]
Workaround is to lower privacy settings to allow 3rd party cookies which allows you to login.

Customers may be thrown by this and not know to lower security settings, can we force it to work somehow?

See crowdsource reporter?

**Comment by MikeTschudi** [comment]
Crowdsource Reporter works when it is hosted in ArcGIS Online; it does not otherwise. This is because we're using an ArcGIS-Online-hosted Twitter proxy.  By hosting an app in that same space, the browser does not see the proxy as a third party. A solution would be to construct a Twitter proxy that can be installed alongside the Photo Survey app (and Crowdsource Reporter if it's to be locally hosted), which would be a bigger task than we can do for the August milestone.

**Comment by busbus** [comment]
Known Issue

**Comment by LindsayThomas** [comment]
#45 is the same issue. 
Happens on IE10 too
