### ISSUE TITLE
Add thumbnaillimit -additional configuration option

### ISSUE THREAD

**Issue by busbus** [Esri/photo-survey#35]
Add thumbnail limit to turn off drawing of thumbnail carousel if property to be surveyed has many photos.

Default to 10 - thumbnaillimit = "10"

**Comment by MikeTschudi** [comment]
New parameter is a number or a string, e.g.,
```
"thumbnailLimit": "2",
```
Any value >= 0--whether number or string---limits the number of thumbnails; otherwise (e.g., empty string or negative value), means no limit on the number of thumbnails. If there's a limit and the number of thumbnails for a location exceeds the limit, then the thumbnail display is hidden for that location.

**Comment by busbus** [comment]
Verified
